apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: cloudflare-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DOMAINS: "{{ .DOMAINS }}"
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"

  dataFrom:
    - extract:
        key: cloudflare