apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: tailscale-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        clientId: "{{ .client_id }}"
        clientSecret: "{{ .client_secret }}"

  dataFrom:
    - extract:
        key: tailscale