---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local
podSubnets:
  - 10.244.0.0/16
serviceSubnets:
  - 10.96.0.0/12

---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false

---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false

---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445

---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
