---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
    namespace: flux-system
  valuesFrom:
    - name: alloy-values
      kind: ConfigMap