write-kubeconfig-mode: "0600"

tls-san:
  - api.astxlab.dev
  - api.cluster.lan
  - "control-2.lan"
  - "100.100.1.4"
  - "192.168.2.4"

cluster-cidr: 10.128.0.0/16
service-cidr: 10.96.0.0/16
cni: none

disable:
  - rke2-coredns
  - rke2-ingress-nginx
  - rke2-metrics-server

disable-cloud-controller: true
disable-kube-proxy: true

enable-servicelb: false