---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./external-secrets.yaml
  - ./grafana-community.yaml
  - ./grafana.yaml
  - ./itzg.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./nextcloud.yaml
  - ./openebs.yaml
  - ./prometheus-community.yaml
  - ./tailscale.yaml
