---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-cluster
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-cluster
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: rook-cluster-values