operatorNamespace: rook-system

cephClusterSpec:
  storage:
    useAllNodes: true
    useAllDevices: false
    devicePathFilter: ^/dev/disk/by-partlabel/r-ceph$

  security:
    cephx:
      allowedCiphers: [aes256k]
      daemon:
        keyRotationPolicy: KeyGeneration
        keyGeneration: 2
      csi:
        keyRotationPolicy: KeyGeneration
        keyGeneration: 2
        keepPriorKeyCountMax: 0
        keyType: aes256k

  cleanupPolicy:
    wipeDevicesFromOtherClusters: true

toolbox:
  enabled: true