apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: nextcloud
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        nextcloud-username: "{{ .username }}"
        nextcloud-password: "{{ .password }}"
        redis-password: "{{ .redis }}"

  dataFrom:
    - extract:
        key: nextcloud