---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template.yaml
  - ./cert-manager.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./flux-operator.yaml
  - ./metrics-server.yaml
components:
  - ../../../components/helm-oci