control-plane:
  hosts:
    control-1:
      ansible_user: hdo
      ansible_host: 192.168.2.3
    control-2:
      ansible_user: hdo
      ansible_host: 192.168.2.4
    control-3:
      ansible_user: hdo
      ansible_host: 192.168.2.5