apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: linkding-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LD_SUPERUSER_NAME: "{{ .username }}"
        LD_SUPERUSER_PASSWORD: "{{ .password }}"
        LD_CSRF_TRUSTED_ORIGINS: "{{ .url }}"
        LD_DB_PASSWORD: "{{ .db_password }}"

  dataFrom:
    - extract:
        key: linkding
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: linkding-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: linkding
        password: "{{ .db_password }}"
      metadata:
        labels:
          cnpg.io/reload: "true"

  dataFrom:
    - extract:
        key: linkding