controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/sissbruecker/linkding
          tag: 1.45.0
        env:
          LD_DB_DATABASE: linkding
          LD_DB_USER: linkding
          LD_ENABLE_AUTH_PROXY: true
          LD_LOG_X_FORWARDED_FOR: true
          LD_DB_ENGINE: postgres
          LD_DB_PORT: 5432
          LD_DB_HOST: postgres-rw.cnpg-system.svc.cluster.local
          LD_AUTH_PROXY_USERNAME_HEADER: HTTP_CF_ACCESS_AUTHENTICATED_USER_EMAIL
        envFrom:
        - secretRef:
            name: linkding-secret
        
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }

        resources:
          requests:
            cpu: 15m
            memory: 250Mi
          limits:
            memory: 250Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 9090

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn
    globalMounts:
      - path: /etc/linkding/data

route:
  app:
    hostnames:
      - "links.astxlab.dev"
    parentRefs:
      - name: web-gateway
        namespace: networking