apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration

networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.128.0.0/16"
  dnsDomain: "cluster.local"

controlPlaneEndpoint: "api.cluster.lan"

apiServer:
  certSANs:
    - "api.cluster.lan"
    - "100.100.1.1"

clusterName: "outer-space"
dns:
  disabled: true
proxy:
  disabled: true

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

cgroupDriver: systemd