apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chalicemc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: chalicemc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WHITELIST: "{{ .whitelist }}"
        OPS: "{{ .ops }}"
  dataFrom:
    - extract:
        key: chalicemc