defaultSettings:
  v2DataEngine: true

  defaultDataPath: /host/dev/disk/by-partlabel/r-longhorn-v2

  storageOverProvisioningPercentage: 200
  replicaSoftAntiAffinity: false
  replicaAutoBalance: least-effort

defaultBackupStore:
  backupTarget: s3://outer-space@auto/
  backupTargetCredentialSecret: longhorn-backup

metrics:
  serviceMonitor:
    enabled: true

httproute:
  enabled: true
  parentRefs:
    - name: web-gateway
      namespace: networking
  hostnames:
    - longhorn.astxlab.dev

persistence:
  dataEngine: v2

  recurringJobSelector:
    enable: true
    jobList: >-
      [{"name":"daily-backup","isGroup":false}]