defaultSettings:

  defaultDataPath: /var/mnt/longhorn/
  defaultReplicaCount: 2

  storageOverProvisioningPercentage: 200
  replicaSoftAntiAffinity: false
  replicaAutoBalance: least-effort

defaultBackupStore:
  backupTarget: s3://outer-space@auto/
  backupTargetCredentialSecret: longhorn-backup

metrics:
  serviceMonitor:
    enabled: true