defaultSettings:

  defaultDataPath: /var/mnt/longhorn

  storageOverProvisioningPercentage: 200
  replicaSoftAntiAffinity: false
  replicaAutoBalance: least-effort

defaultBackupStore:
  backupTarget: s3://outer-space@auto/
  backupTargetCredentialSecret: longhorn-backup

metrics:
  serviceMonitor:
    enabled: true

httproute:
  enabled: true
  parentRefs:
    - name: web-gateway
      namespace: networking
  hostnames:
    - longhorn.astxlab.dev

persistence:
  dataEngine: v1
  recurringJobSelector:
    jobList: 
    - { "name":"backups", "isGroup":true }
  