variant: fcos
version: 1.6.0

storage:
  disks:
    - # Block device the OS was booted from
      device: /dev/disk/by-id/coreos-boot-disk
      wipe_table: false
      partitions:
        - label: root
          number: 4
          size_mib: 32768

        - label: var
          size_mib: 65535

        - label: ceph-block
          size_mib: 0

  filesystems:
    - device: /dev/disk/by-partlabel/var
      path: /var
      format: xfs
      with_mount_unit: true

  files:
    - path: /etc/hostname
      mode: 0644
      overwrite: true
      contents:
        inline: control-3
    
    - path: /etc/yum.repos.d/kubernetes.repo
      mode: 0644
      overwrite: true
      contents:
        local: common/repo/kubernetes.repo

    - path: /etc/yum.repos.d/cri-o.repo
      mode: 0644
      overwrite: true
      contents:
        local: common/repo/cri-o.repo

passwd:
  users:
    - name: core
      ssh_authorized_keys_local:
        - common/users/core/id_ed25519.pub

    - name: hdo
      groups:
        - wheel
        - sudo
      ssh_authorized_keys_local:
        - common/users/hdo/id_ed25519.pub

systemd:
  units:
    - name: install-k8s.service
      enabled: true
      contents_local: common/units/install-k8s.service

    - name: crio.service
      enabled: true

    - name: kubelet.service
      enabled: true