---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: prometheus-stack
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  valuesFrom:
    - name: prometheus-values
      kind: ConfigMap