---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: osd
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  minSize: 1280GiB
  maxSize: 1280GiB

---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL

provisioning:
  diskSelector:
    match: system_disk
  minSize: 300GiB
  maxSize: 300GiB