apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: infisical-auth
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: outer-space
        environmentSlug: prod