---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cnpg-values
