apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: longhorn-backup
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: "{{ .AWS_ENDPOINTS }}"

  dataFrom:
    - extract:
        key: longhorn-backup