---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: loki
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  valuesFrom:
    - name: loki-values
      kind: ConfigMap