---
serviceMonitor:
  create: true

web:
  enabled: true
  # httpRoute:
  #   enabled: true
  #   hostnames:
  #     - flux.astxlab.dev
  #   parentRefs:
  #   - name: web-gateway
  #     namespace: networking