apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        nextcloud-username: "{{ .username }}"
        nextcloud-password: "{{ .password }}"
        redis-password: "{{ .redis }}"
        mariadb-root-password: "{{ .mariadb-root-password }}"
        mariadb-replication-password: "{{ .mariadb-replication-password }}"
        mariadb-password: "{{ .mariadb-password }}"
        


  dataFrom:
    - extract:
        key: nextcloud