nextcloud:
  host: files.astxlab.dev
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
  configs:
    overwrite.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://files.astxlab.dev',
        'overwritehost' => 'files.astxlab.dev',
      );

    proxies.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' =>
        array (
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
          2 => '192.168.0.0/16',
        ),
        'forwarded_for_headers' =>
        array (
          0 => 'HTTP_X_FORWARDED_FOR',
        ),
      );

    domains.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' =>
        array (
          0 => 'localhost',
          1 => 'files.astxlab.dev',
          2 => 'nextcloud.nextcloud.svc.cluster.local',
        ),
      );

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: nextcloud-secret
    existingSecretPasswordKey: redis-password

mariadb:
  enabled: true
  auth:
    existingSecret: nextcloud-secret
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 20Gi

externalDatabase:
  enabled: true

internalDatabase:
  enabled: false

persistence:
  enabled: true
  storageClass: longhorn
  size: 100Gi

phpClientHttpsFix:
  enabled: true

# metrics:
#   enabled: true
#   https: true

# prometheus:
#   serviceMonitor:
#     enabled: true
